## Insider Threat Radar – Behavior Analytics for Employee Risk Prediction

### Data Loading

#### Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

#### File Paths

In [2]:
email_path = "../Dataset/email.csv"
psycho_path = "../Dataset/psychometric.csv"

#### Load Datasets

In [3]:
email_df = pd.read_csv(email_path)
psycho_df = pd.read_csv(psycho_path)

print("Email Dataset Loaded ✅")
print("Psychometric Dataset Loaded ✅")

Email Dataset Loaded ✅
Psychometric Dataset Loaded ✅

#### Basic Inspection (Email)

In [4]:
print("EMAIL DATASET")
print("Shape:", email_df.shape)
display(email_df.head())
email_df.info()

EMAIL DATASET
Shape: (2629979, 11)

,id,date,user,pc,to,cc,bcc,from,size,attachments,content
0,{R3I7-S4TX96FG-8219JWFF},01/02/2010 07:11:45,LAP0338,PC-5758,Dean.Flynn.Hines@dtaa.com;Wade_Harrison@lockhe...,Nathaniel.Hunter.Heath@dtaa.com,NaN,Lynn.Adena.Pratt@dtaa.com,25830,0,middle f2 systems 4 july techniques powerful d...
1,{R0R9-E4GL59IK-2907OSWJ},01/02/2010 07:12:16,MOH0273,PC-6699,Odonnell-Gage@bellsouth.net,NaN,NaN,MOH68@optonline.net,29942,0,the breaking called allied reservations former...
2,{G2B2-A8XY58CP-2847ZJZL},01/02/2010 07:13:00,LAP0338,PC-5758,Penelope_Colon@netzero.com,NaN,NaN,Lynn_A_Pratt@earthlink.net,28780,0,slowly this uncinus winter beneath addition ex...
3,{A3A9-F4TH89AA-8318GFGK},01/02/2010 07:13:17,LAP0338,PC-5758,Judith_Hayden@comcast.net,NaN,NaN,Lynn_A_Pratt@earthlink.net,21907,0,400 other difficult land cirrocumulus powered ...
4,{E8B7-C8FZ88UF-2946RUQQ},01/02/2010 07:13:28,MOH0273,PC-6699,Bond-Raymond@verizon.net;Alea_Ferrell@msn.com;...,NaN,Odonnell-Gage@bellsouth.net,MOH68@optonline.net,17319,0,this kmh october holliswood number advised unu...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2629979 entries, 0 to 2629978
Data columns (total 11 columns):
 #   Column       Dtype
---  ------       -----
 0   id           object
 1   date         object
 2   user         object
 3   pc           object
 4   to           object
 5   cc           object
 6   bcc          object
 7   from         object
 8   size         int64
 9   attachments  int64
 10  content      object
dtypes: int64(2), object(9)
memory usage: 220.7+ MB

#### Basic Inspection (Psychometric)

In [5]:
print("PSYCHOMETRIC DATASET")
print("Shape:", psycho_df.shape)
display(psycho_df.head())
psycho_df.info()

PSYCHOMETRIC DATASET
Shape: (1000, 7)

             employee_name  user_id   O   C   E   A   N
0         Calvin Edan Love  CEL0561  40  39  36  19  40
1  Christine Reagan Deleon  CRD0624  26  22  17  39  32
2    Jade Felicia Caldwell  JFC0557  22  16  23  40  33
3   Aquila Stewart Dejesus  ASD0577  40  48  36  14  37
4        Micah Abdul Rojas  MAR0955  36  44  23  44  25

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_name  1000 non-null   object
 1   user_id        1000 non-null   object
 2   O              1000 non-null   int64
 3   C              1000 non-null   int64
 4   E              1000 non-null   int64
 5   A              1000 non-null   int64
 6   N              1000 non-null   int64
dtypes: int64(5), object(2)
memory usage: 54.8+ KB

#### Check Missing Values

In [6]:
print("Missing Values - Email")
print(email_df.isnull().sum())

print("\nMissing Values - Psychometric")
print(psycho_df.isnull().sum())

Missing Values - Email
id                   0
date                 0
user                 0
pc                   0
to                   0
cc             1617054
bcc            2212977
from                 0
size                 0
attachments          0
content              0
dtype: int64

Missing Values - Psychometric
employee_name    0
user_id          0
O                0
C                0
E                0
A                0
N                0
dtype: int64

#### Duplicate Check

In [7]:
print("Duplicate rows - Email:", email_df.duplicated().sum())
print("Duplicate rows - Psychometric:", psycho_df.duplicated().sum())

Duplicate rows - Email: 0
Duplicate rows - Psychometric: 0

#### Column Names

In [8]:
print("Email Columns:\n", email_df.columns)
print("\nPsychometric Columns:\n", psycho_df.columns)

Email Columns:
 Index(['id', 'date', 'user', 'pc', 'to', 'cc', 'bcc', 'from', 'size',
       'attachments', 'content'],
      dtype='object')

Psychometric Columns:
 Index(['employee_name', 'user_id', 'O', 'C', 'E', 'A', 'N'], dtype='object')